### ISSUE TITLE
Sublime - Align JSON formatting

### ISSUE THREAD

**Issue by yairEO** [shammond42/cheater#6]
Doesn't seem to work for me... `Ctrl + Alt + J` to "Align JSON formatting"

input:

```
{a:1,b:[2,3.4], z:function(){}}
```

---

sublime v3 build 3083

**Comment by shammond42** [comment]
Are you perhaps posting this in the wrong project? All cheater does is show you a cheat sheet of commands. It doesn't actually implement any of those commands.
